name: Python Script Run

on:
  push:
    branches:
      - master # Trigger workflow on pushes to the master branch

jobs:
  run-pandas-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      # Step 4: Run the script
      - name: Run Pandas Script
        run: python main.py
